### ISSUE TITLE
bme280の初期化処理でコンテナが停止する

### ISSUE THREAD

**Issue by kmchord9** [kmchord9/raspi_phpmyadmin#1]
node-red_1    | Found BMx280 chip ID 0x60 on bus i2c-1, address 0x76
node-red_1    | 1 Sep 06:01:10 - [red] Uncaught Exception:
node-red_1    | 1 Sep 06:01:10 - Error: , Remote I/O error
node-red_1    |     at Bus.readByteSync (/usr/src/node-red/node_modules/i2c-bus/i2c-bus.js:289:16)
node-red_1    |     at /usr/src/node-red/node_modules/bme280-sensor/BME280.js:179:30
node-red_1    | npm ERR! code ELIFECYCLE
node-red_1    | npm ERR! errno 1
node-red_1    | npm ERR! node-red-docker@2.0.5 start: `node $NODE_OPTIONS node_modules/node-red/red.js $FLOWS "--userDir" "/data" "node-red"`
node-red_1    | npm ERR! Exit status 1
node-red_1    | npm ERR!
node-red_1    | npm ERR! Failed at the node-red-docker@2.0.5 start script.
node-red_1    | npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
node-red_1    |
node-red_1    | npm ERR! A complete log of this run can be found in:
node-red_1    | npm ERR!     /data/.npm/_logs/2021-09-01T06_01_11_042Z-debug.log
raspi_phpmyadmin_node-red_1 exited with code 1

**Comment by kmchord9** [comment]
再現環境

Welcome to Node-RED
===================

1 Sep 06:04:50 - [info] Node-RED version: v2.0.5
1 Sep 06:04:50 - [info] Node.js  version: v14.17.3
1 Sep 06:04:50 - [info] Linux 5.10.17-v7+ arm LE
1 Sep 06:04:51 - [info] Loading palette nodes
1 Sep 06:04:54 - [info] Settings file  : /data/settings.js
1 Sep 06:04:54 - [info] Context store  : 'default' [module=memory]
1 Sep 06:04:54 - [info] User directory : /data
1 Sep 06:04:54 - [warn] Projects disabled : editorTheme.projects.enabled=false
1 Sep 06:04:54 - [info] Flows file     : /data/flows.json
1 Sep 06:04:54 - [info] Server now running at http://127.0.0.1:1880/
1 Sep 06:04:54 - [warn]

---------------------------------------------------------------------
Your flow credentials file is encrypted using a system-generated key.

If the system-generated key is lost for any reason, your credentials
file will not be recoverable, you will have to delete it and re-enter
your credentials.

You should set your own key using the 'credentialSecret' option in
your settings file. Node-RED will then re-encrypt your credentials
file using your chosen key the next time you deploy a change.
---------------------------------------------------------------------

1 Sep 06:04:54 - [info] Starting flows
1 Sep 06:04:54 - [info] Started flows

**Comment by kmchord9** [comment]
bash-5.0$ npm install node-red-contrib-bme280

> i2c-bus@5.2.2 install /usr/src/node-red/node_modules/i2c-bus
> node-gyp rebuild

make: Entering directory '/usr/src/node-red/node_modules/i2c-bus/build'
  CXX(target) Release/obj.target/i2c/src/i2c.o
  SOLINK_MODULE(target) Release/obj.target/i2c.node
  COPY Release/i2c.node
make: Leaving directory '/usr/src/node-red/node_modules/i2c-bus/build'
npm notice created a lockfile as package-lock.json. You should commit this file.
+ node-red-contrib-bme280@1.0.0
added 6 packages from 11 contributors and audited 295 packages in 63.337s

27 packages are looking for funding
  run `npm fund` for details

found 12 high severity vulnerabilities
  run `npm audit fix` to fix them, or `npm audit` for details
